### ISSUE TITLE
a3c worker exited unexpectedly

### ISSUE THREAD

**Issue by xfdywy** [ShangtongZhang/DeepRL#11]
I can run your dqn code under pytorch=v0.2, but the a3c seems cannot run correctly.  It always logs that 
      worker xxx exited unexpectedly
      worker xxx restarted
xxx is the different process numbers.

But when I switch to pytorch v0.1.12. a3c seems partially correct. There still "worker xxx exited unexpectedly worker xxx restarted" log in some process, but much less.  And I can see the log print something like "total step" and "averaged return". Is it a known bug? Do you know why this happens?

**Comment by ShangtongZhang** [comment]
See this https://github.com/ShangtongZhang/DeepRL/issues/7
There is some bugs in pytorch in 0.2, so it doesn't work

And in 0.1.12, it works well in my machine. I don't know what you mean by `much less` exactly. I tried to run my a3c in a server, after several hours or one day, I can get some `worker xxx exited unexpectedly`. The worker was killed by `OOM` (out of memory) according to the system log, so I believe there is some memory leak, but I cannot find it. That's why I launch an extra thread to check whether the workers are working and restart it if necessary.

**Comment by xfdywy** [comment]
Hah, your a3c code can run under Python 3.5. No exited unexpectedly, No segment fault!

**Comment by ShangtongZhang** [comment]
Interesting .... stupid python
