### ISSUE TITLE
set_one_thread() in example.py

### ISSUE THREAD

**Issue by jyf588** [ShangtongZhang/DeepRL#63]
Hello Shangtong,

Sorry to interrupt you but I am new to pytorch. A quick question - what is the purpose of set_one_thread() in example.py? Is it simply equivalent to setting num_workers = 1 ? Am I understanding your code correctly that every time I want to run an algorithm with num_workers>1, I should comment out set_one_thread()?

**Comment by ShangtongZhang** [comment]
No. Always use ```set_one_thread```. It's for OpenMP and MKL.

**Comment by jyf588** [comment]
So if I want to use multiple (>1) workers/cores, I should comment out `set_one_thread`, right?

**Comment by ShangtongZhang** [comment]
no. never comment it out.

Shangtong Zhang

**Comment by jyf588** [comment]
I should have made this clearer - the reason I was asking is that, when I run `python example.py`, even if num_workers>1, the machine still only uses one core. I can only get my machine use multiple cores with `set_one_thread` commented out. 

Am I misunderstanding how to use your code? Thanks.

**Comment by ShangtongZhang** [comment]
'num_workers > 1' does not necessarily mean we need to start multiple threads. I use one single thread to simulate multiple workers. This usually makes better use of CPU resources — you can run multiple seeds simultaneously. Unless you have hundreds of CPUs, I do not expect the ‘real multiple workers’ can help in terms of overall experiment time. If you want to use real multiple workers, set this flag to False (but I haven’t used it for quite long time):
https://github.com/ShangtongZhang/DeepRL/blob/master/deep_rl/component/envs.py#L157 <https://github.com/ShangtongZhang/DeepRL/blob/master/deep_rl/component/envs.py#L157>

If you comment ’set_one_thread’ out, it means you allow pytorch to do things like matrix multiplication with multiple threads — it has nothing to do with multiple workers.  I find this does not help — I would rather run multiple seeds simultaneously instead of doing matrix multiplication with multiple threads.

Shangtong Zhang,
DPhil Student,
Department of Computer Science,
University of Oxford

**Comment by ShangtongZhang** [comment]
Now this ```set_one_thread``` is removed, and that functionality is implemented in 
https://github.com/ShangtongZhang/DeepRL/blob/master/docker_python.sh#L9
