### ISSUE TITLE
Some questions about DAC

### ISSUE THREAD

**Issue by Sunkworld** [ShangtongZhang/DeepRL#69]
Hi, thank you for reading our replication report of the DAC paper.

About the random seed problem, I see in https://github.com/ShangtongZhang/DeepRL/blob/32bd11e9f01ef5e473d58d0bf64b89ad196e5727/template_jobs.py#L59 that 10 runs are done in the same program, so that the random seed for a single task will be the same for these 10 runs. Is there something I misunderstand about the procedure?

Another question is about https://github.com/ShangtongZhang/DeepRL/blob/32bd11e9f01ef5e473d58d0bf64b89ad196e5727/deep_rl/agent/ASquaredC_PPO_agent.py#L125 where the calculation of V for high&low level MDPs seems to be in contrast to the definition in paper, as well as the calculation at https://github.com/ShangtongZhang/DeepRL/blob/32bd11e9f01ef5e473d58d0bf64b89ad196e5727/deep_rl/agent/ASquaredC_PPO_agent.py#L215 Am I missing something here? Thank you.

**Comment by ShangtongZhang** [comment]
https://github.com/ShangtongZhang/DeepRL/blob/32bd11e9f01ef5e473d58d0bf64b89ad196e5727/template_jobs.py#L83
For each container, only one of the ```params``` is executed (there is no loop over ```cf.i```), so that random seed bug shouldn't have any influence.

https://github.com/ShangtongZhang/DeepRL/blob/32bd11e9f01ef5e473d58d0bf64b89ad196e5727/deep_rl/agent/ASquaredC_PPO_agent.py#L125
I think this is a bug :< Thanks a lot for pointing it out. In my understanding this bug shouldn't make a big difference. It only influences the value function update. The two actors share the same value function and I use the same data for the two MDPs. So the order of updating value function isn't very important. Just pushed a fix.

**Comment by Sunkworld** [comment]
As I understand, v_h is the value function per state, while v_l is the value function per state+option, and they're used in calculating advantages for the high/low actors respectively, so there should be some differences conceptually. It's interesting that practically they seem interchangeable lol.
